# Generated by Django 5.0.1 on 2024-01-25 19:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('father_name', models.TextField(default='Rahim')),
                ('binary_field', models.BinaryField(default=b'')),
                ('boolean_field', models.BooleanField(default=True)),
                ('char_field', models.CharField(default='', max_length=255)),
                ('time_field', models.TimeField(default=django.utils.timezone.now)),
                ('date_field', models.DateField(default=django.utils.timezone.now)),
                ('date_time_field', models.DateTimeField(default=django.utils.timezone.now)),
                ('decimal_field', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('duration_field', models.DurationField(default=datetime.timedelta(0))),
                ('email_field', models.EmailField(default='test@gmail.com', max_length=254)),
                ('file_field', models.FileField(default='default_file.txt', upload_to='files/')),
                ('file_path_field', models.FilePathField(default='/path/to/files/default_file.txt', path='/path/to/files/')),
                ('float_field', models.FloatField(default=0.0)),
                ('generic_ip_address_field', models.GenericIPAddressField(default='127.0.0.1')),
                ('image_field', models.ImageField(default='', upload_to='images/')),
                ('json_field', models.JSONField(default=dict)),
                ('positive_big_integer_field', models.PositiveBigIntegerField(default=25)),
                ('positive_integer_field', models.PositiveIntegerField(default=20)),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(default=10)),
                ('slug_field', models.SlugField(default='default-slug')),
                ('small_integer_field', models.SmallIntegerField(default=5)),
                ('url_field', models.URLField(default='https://google.com')),
            ],
        ),
    ]
