# Generated by Django 5.0.1 on 2024-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_remove_student_father_name_alter_student_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_field',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_time_field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=2500999999999),
        ),
        migrations.AlterField(
            model_name='student',
            name='positive_integer_field',
            field=models.PositiveIntegerField(default=29990),
        ),
        migrations.AlterField(
            model_name='student',
            name='time_field',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
