# Generated by Django 5.0.1 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0003_alter_student_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='positive_integer_field',
            field=models.PositiveIntegerField(default=29999999990),
        ),
    ]
